---
body:
  - type: dropdown
    id: component
    attributes:
      label: What product would you like to leave feedback for?
      options:
        - Console
        - Fast Data
        - Marketplace
        - Microfrontend Composer
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: What Console version are you using?
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Share here your feedback on Mia-Platform product features"
    validations:
      required: true
