---
body:
  - type: dropdown
    id: component
    attributes:
      label: What product are you having troubles with?
      options:
        - Console
        - Fast Data
        - Marketplace
        - Microfrontend Composer
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: What Console version are you using?
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Write your question here..."
    validations:
      required: true
  - type: textarea
    id: actual-outcome
    attributes:
      label: Actual Outcome
      description: "Describe the actual outcome you are experiencing"
  - type: textarea
    id: expected-outcome
    attributes:
      label: Expected Outcome
      description: "Describe the outcome you would expect"
