name: "discussion-webhook"
on:
  discussion:
    types: ["created", "answered", "unanswered"]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: "Google Chat notification"
        run: |
          title="${{ github.event.discussion.title }}"
          escaped_title="${title//\'/\\\'}"
          [ $(curl --location -X POST '${{secrets.WEBHOOK_CHAT_URL}}&messageReplyOption=REPLY_MESSAGE_FALLBACK_TO_NEW_THREAD' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "thread": {
                  "threadKey": "416"
              },
              "cardsV2": [
                  {
                      "cardId": "discussion-card",
                      "card": {
                          "header": {
                              "title": "Discussion #416 is created",
                              "subtitle": "Discussion tracker bot"
                          },
                          "sections": {
                              "widgets": [
                                  {
                                      "decoratedText": {
                                          "topLabel": "Title",
                                          "text": "<b>${escaped_title}</b>",
                                          "bottomLabel": "User: 10374360"
                                      }
                                  },
                                  {
                                      "decoratedText": {
                                          "topLabel": "Category",
                                          "text": "Q&A"
                                      }
                                  },
                                  {
                                      "buttonList": {
                                          "buttons": [
                                              {
                                                  "text": "OPEN DISCUSSION",
                                                  "onClick": {
                                                      "openLink": {
                                                          "url": "https://github.com/mia-platform/community/discussions/416"
                                                      }
                                                  }
                                              }
                                          ]
                                      }
                                  }
                              ]
                          }
                      }
                  }
              ]
          }' -o /dev/null -w '%{http_code}') -eq 200 ]
