name: "discussion-webhook"
on:
  discussion:
    types: ["created", "answered", "unanswered"]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: "Google Chat notification"
        run: |
          title="${{ github.event.discussion.title }}"
          escaped_title="${title//\'/\\\'}"
          [ $(curl --location -X POST '${{secrets.WEBHOOK_CHAT_URL}}&messageReplyOption=REPLY_MESSAGE_FALLBACK_TO_NEW_THREAD' \
          --header 'Content-Type: application/json' \
          --data-raw '{
            "thread": {"threadKey": "${{github.event.discussion.number}}"}
            "cardsV2": [{
              "header": {
                "title": "Discussion #${{ github.event.discussion.number }} is ${{ github.event.action }}",
                "subtitle": "Discussion tracker bot"
              },
              "sections": {
                "widgets": [
                  {
                    "decoratedText": {
                      "topLabel": "Title",
                      "text": "<b>${escaped_title}</b>",
                      "bottomLabel": "User: ${{ github.event.discussion.user.id }}",
                    }
                  },
                  {
                    "decoratedText": {
                      "topLabel": "Category",
                      "text": "${{ github.event.discussion.category.name }}"
                    }
                  },
                  {
                    "buttonList": {
                      "buttons": [
                        {
                          "text": "OPEN DISCUSSION",
                          "onClick": {
                            "openLink": {
                              "url": "${{github.event.discussion.html_url}}"
                            }
                          }
                        }
                      ]
                    }
                  }
                ]
              }
            }]
          }' -o /dev/null -w '%{http_code}') -eq 200 ]
